image:
  # Specify the Java version you want to use
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install openjdk-21-jdk
  - command: |
      java -version  # To verify the Java version is updated

